[package]
name = "uxn-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitmask-enum = "2.0.0"
custom_derive = "0.1.7"
enum_derive = "0.1.7"
nom = "7"
